apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml

labels:
  - pairs:
      app.kubernetes.io/name: metrics-server
      app.kubernetes.io/managed-by: argocd
